PWD=$(shell pwd)
CGI_PATH=$(PWD)/htdocs/cgi_bin/
SER_BIN=http
SER_SRC=httpd.c
CLI_BIN=client
CLI_SRC=client.c
INCLUDE=
CC=gcc
FLAGS=-o
LDFLAGS=-lpthread

.PHONY:all
all:$(SER_BIN) $(CLI_BIN) cgi
$(SER_BIN):$(SER_SRC)
	@$(CC) $(FLAGS) $@ $^ $(LDFLAGS) -D_DEBUG_ -g
$(CLI_BIN):$(CLI_SRC)
	@$(CC) $(FLAGS) $@ $^ -D_DEBUG_ -g -w

.PHONY:cgi
cgi:
	@cd htdocs/cgi_bin;\
	for name in `ls`;\
	do\
		cd $$name;\
		make;\
		cd ..;\
	done;\


	#for name in `echo $(CGI_PATH)`;\
	#do\
	#	cd $$name;\
	#	make;\
	#	cd -;\
	#done

.PHONY:cls
cls:
	rm -rf $(SER_BIN) $(CLI_BIN)

.PHONY:clean
clean:cleancgi
	make cls;\


cleancgi:
	@cd htdocs/cgi_bin;\
	for name in `ls`;\
	do\
		cd $$name;\
		make clean;\
		cd ..;\
	done;\


	#@rm -rf $(SER_BIN) $(CLI_BIN) 
	#for name in `ls $(CGI_PATH)`
	#do\
	#	cd $$name;\
	#	make clean;\
	#	cd ..;\
	#done
#clean:
#	@rm -rf $(SER_BIN) $(CLI_BIN) 
#	@for name in `ls $(CGI_PATH)`;\
#	do\
#		cd $$name;\
#		make clean;\
#		cd -;\
#	done

.PHONY:git
git:clean
	git add *
	git commit -m "`date +%y/%m/%d/%R`"
	git push -u origin master

#.PHONY:cleanall
#cleanall:
#	@cd ./htdocs/cgi_bin;\
#	for name in `ls`;\
#	do\
#		cd $$name;\
#		make clean;\
#		cd -;\
#	done
#	@cd ../../;\
#	make clean;\

