.PHONY:all
all:weixin

weixin:weixin.cpp
	:

output:all
	:
#	g++ -o $@ $^ /mnt/hgfs/Buffer/jsoncpp-src-0.5.0/libs/linux-gcc-4.4.7/libjson_linux-gcc-4.4.7_libmt.a
#
#.PHONY:output
#output:all
#	cp weixin ../../output/htdocs/cgi_bin/
#
#.PHONY:clean
#clean:
#	rm -rf weixin
