#!/bin/bash

echo "<html>"
echo "<title>date</title>"
echo "<body>"
echo "<h1>today is:"
echo `date +%y/%m/%d`
echo "</h1>"
echo "</body>"
echo "</html>"
echo "<form action=\"../index.html\">"
echo "<input type=\"submit\" value=\"goto home\"/><br/>"
echo "</form>"
